
import {
  ExpenseReimbursementIcon,
  MasterPolicyIcon,
  FormsIcon,
  LeaveIcon,
  DisciplinaryIcon,
  GrievanceIcon,
  HealthSafetyIcon,
  UifIcon,
  TerminationOfEmploymentIcon,
  RecruitmentSelectionIcon,
  SexualHarassmentIcon,
  ElectronicCommunicationsIcon,
  CompanyVehicleIcon,
  ConfidentialityIcon,
  DataProtectionPrivacyIcon,
  RemoteWorkIcon,
  ByodIcon,
  WorkingHoursIcon,
  DressCodeIcon,
  AttendancePunctualityIcon,
  EmploymentEquityIcon,
  TrainingDevelopmentIcon,
  WhistleblowerIcon,
  AlcoholDrugIcon,
  IncidentReportIcon,
  JobDescriptionIcon,
  LeaveApplicationIcon,
  AntiBriberyCorruptionIcon,
  AntiBullyingIcon,
  AntiHarassmentDiscriminationIcon,
  CellPhoneIcon,
  CertificationIcon,
  CodeOfEthicsIcon,
  CoidaIcon,
  CommunicationRetentionIcon,
  CompanyPropertyIcon,
  CompensationBenefitsIcon,
  ConflictOfInterestIcon,
  DataUsageIcon,
  DeductionsIcon,
  DisciplinaryActionIcon,
  EeoDiversityIcon,
  EmployeeConductIcon,
  EmployeeSeparationIcon,
  FamilyResponsibilityLeaveIcon,
  ItAccessSecurityIcon,
  ItCybersecurityIcon,
  LanguagePolicyIcon,
  PerformanceManagementIcon,
  RecordsRetentionIcon,
  ResignationIcon,
  RetrenchmentIcon,
  SalaryStructureIcon,
  SecurityIcon,
  SocialMediaIcon,
  StandbyIcon,
  TelephoneUsageIcon,
  TimeOffIcon,
  TravelIcon,
  VisitorIcon,
  WorkplaceWellnessIcon,
  AppealFormIcon,
  CandidateEvaluationIcon,
  CertificateOfServiceIcon,
  ChecklistIcon,
  EmploymentContractIcon,
  ExitInterviewIcon,
  ExpenseClaimIcon,
  FinalWrittenWarningIcon,
  InterviewGuideIcon,
  JobAdvertisementIcon,
  JobApplicationIcon,
  LegalNoticeIcon,
  MaternityLeaveIcon,
  MeetingMinutesIcon,
  OnboardingChecklistIcon,
  OvertimeClaimIcon,
  PayrollProcessingIcon,
  PerformanceReviewIcon,
  PermissionForDeductionsIcon,
  ReferenceCheckIcon,
  RegisterIcon,
  RestraintOfTradeIcon,
  RetrenchmentNoticeIcon,
  SalaryBankIcon,
  SkillsDevelopmentIcon,
  SuspensionNoticeIcon,
  TrainingAgreementIcon,
  EmployeeDetailsIcon,
  CleaningIcon,
  FoodSafetyIcon,
  TemperatureIcon,
  TrainingRegisterIcon,
  CanvaIcon,
  AfrikaansIcon,
  BundleIcon,
  SurveyIcon,
} from './components/Icons';
import type { Policy, Form, Question, PolicyType, FormType } from './types';

export const INDUSTRIES = [
  'Agriculture',
  'Construction',
  'Education',
  'Finance',
  'Health',
  'Hospitality',
  'Manufacturing',
  'Mining',
  'Professional Services',
  'Retail',
  'Technology',
  'Transport',
  'Other'
];

export const commonQuestions: Question[] = [
  { id: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
];

export const commonPolicyMetadataQuestions: Question[] = [
  { id: 'responsiblePerson', label: 'Responsible Person (Role)', type: 'text', placeholder: 'e.g., HR Manager' },
];

export const POLICIES: Record<string, Policy> = {
  'expense-reimbursement': {
    kind: 'policy',
    type: 'expense-reimbursement',
    title: 'Expense Reimbursement Policy',
    description: 'Procedures for claiming business-related expenses.',
    icon: ExpenseReimbursementIcon,
    price: 3500,
    questions: [
      ...commonQuestions,
      ...commonPolicyMetadataQuestions,
      { id: 'reimbursementTimeframe', label: 'Typical timeframe for reimbursement (days)', type: 'number', placeholder: 'e.g., 14' },
      { id: 'receiptThreshold', label: 'Minimum amount requiring receipt (R)', type: 'number', placeholder: 'e.g., 50', tip: 'Expenses below this amount may not strictly require a slip, though recommended.' }
    ],
  },
  'disciplinary': { kind: 'policy', type: 'disciplinary', title: 'Disciplinary Code', description: 'Rules and procedures for discipline.', icon: DisciplinaryIcon, price: 3500, questions: commonQuestions },
  'grievance': { kind: 'policy', type: 'grievance', title: 'Grievance Procedure', description: 'Handling employee complaints.', icon: GrievanceIcon, price: 3500, questions: commonQuestions },
  'leave': { kind: 'policy', type: 'leave', title: 'Leave Policy', description: 'Annual, sick, and family leave rules.', icon: LeaveIcon, price: 3500, questions: commonQuestions },
  'health-and-safety': { kind: 'policy', type: 'health-and-safety', title: 'Health & Safety Policy', description: 'Workplace safety guidelines.', icon: HealthSafetyIcon, price: 3500, questions: commonQuestions },
  'uif': { kind: 'policy', type: 'uif', title: 'UIF Policy', description: 'Unemployment Insurance Fund details.', icon: UifIcon, price: 2500, questions: commonQuestions },
  'termination-of-employment': { kind: 'policy', type: 'termination-of-employment', title: 'Termination Policy', description: 'Procedures for ending employment.', icon: TerminationOfEmploymentIcon, price: 3500, questions: commonQuestions },
  'sexual-harassment': { kind: 'policy', type: 'sexual-harassment', title: 'Sexual Harassment Policy', description: 'Zero-tolerance approach to harassment.', icon: SexualHarassmentIcon, price: 3500, questions: commonQuestions },
  'electronic-communications': { kind: 'policy', type: 'electronic-communications', title: 'Electronic Communications Policy', description: 'Email and internet usage rules.', icon: ElectronicCommunicationsIcon, price: 3500, questions: commonQuestions },
  'recruitment-selection': { kind: 'policy', type: 'recruitment-selection', title: 'Recruitment Policy', description: 'Fair hiring practices.', icon: RecruitmentSelectionIcon, price: 3500, questions: commonQuestions },
  'company-vehicle': { kind: 'policy', type: 'company-vehicle', title: 'Company Vehicle Policy', description: 'Rules for using company cars.', icon: CompanyVehicleIcon, price: 3500, questions: commonQuestions },
  'confidentiality': { kind: 'policy', type: 'confidentiality', title: 'Confidentiality Policy', description: 'Protecting company information.', icon: ConfidentialityIcon, price: 3500, questions: commonQuestions },
  'data-protection-privacy': { kind: 'policy', type: 'data-protection-privacy', title: 'Data Protection (POPIA) Policy', description: 'Compliance with POPIA.', icon: DataProtectionPrivacyIcon, price: 3500, questions: commonQuestions },
  'remote-hybrid-work': { kind: 'policy', type: 'remote-hybrid-work', title: 'Remote Work Policy', description: 'Guidelines for working from home.', icon: RemoteWorkIcon, price: 3500, questions: commonQuestions },
  'byod': { kind: 'policy', type: 'byod', title: 'BYOD Policy', description: 'Bring Your Own Device rules.', icon: ByodIcon, price: 3500, questions: commonQuestions },
  'working-hours': { kind: 'policy', type: 'working-hours', title: 'Working Hours Policy', description: 'Shifts, overtime, and breaks.', icon: WorkingHoursIcon, price: 3500, questions: commonQuestions },
  'dress-code': { kind: 'policy', type: 'dress-code', title: 'Dress Code Policy', description: 'Attire standards.', icon: DressCodeIcon, price: 2500, questions: commonQuestions },
  'attendance-punctuality': { kind: 'policy', type: 'attendance-punctuality', title: 'Attendance Policy', description: 'Rules for attendance and punctuality.', icon: AttendancePunctualityIcon, price: 3500, questions: commonQuestions },
  'employment-equity': { kind: 'policy', type: 'employment-equity', title: 'Employment Equity Policy', description: 'Promoting diversity and equity.', icon: EmploymentEquityIcon, price: 4500, questions: commonQuestions },
  'training-development': { kind: 'policy', type: 'training-development', title: 'Training & Development Policy', description: 'Employee skills development.', icon: TrainingDevelopmentIcon, price: 3500, questions: commonQuestions },
  'whistleblower': { kind: 'policy', type: 'whistleblower', title: 'Whistleblower Policy', description: 'Reporting unethical conduct.', icon: WhistleblowerIcon, price: 3500, questions: commonQuestions },
  'alcohol-drug': { kind: 'policy', type: 'alcohol-drug', title: 'Substance Abuse Policy', description: 'Alcohol and drug regulations.', icon: AlcoholDrugIcon, price: 3500, questions: commonQuestions },
  'coida': { kind: 'policy', type: 'coida', title: 'COIDA Policy', description: 'Compensation for Occupational Injuries and Diseases.', icon: CoidaIcon, price: 3500, questions: commonQuestions },
  'social-media': { kind: 'policy', type: 'social-media', title: 'Social Media Policy', description: 'Guidelines for professional social media use.', icon: SocialMediaIcon, price: 3500, questions: commonQuestions },
  'anti-bribery-corruption': { kind: 'policy', type: 'anti-bribery-corruption', title: 'Anti-Bribery & Corruption', description: 'Zero tolerance for corruption.', icon: AntiBriberyCorruptionIcon, price: 3500, questions: commonQuestions },
  'anti-bullying': { kind: 'policy', type: 'anti-bullying', title: 'Anti-Bullying Policy', description: 'Preventing workplace bullying.', icon: AntiBullyingIcon, price: 3500, questions: commonQuestions },
  'anti-harassment-discrimination': { kind: 'policy', type: 'anti-harassment-discrimination', title: 'Anti-Harassment Policy', description: 'Preventing discrimination and harassment.', icon: AntiHarassmentDiscriminationIcon, price: 3500, questions: commonQuestions },
  'cell-phone': { kind: 'policy', type: 'cell-phone', title: 'Cell Phone Policy', description: 'Rules for mobile phone usage at work.', icon: CellPhoneIcon, price: 2500, questions: commonQuestions },
  'code-of-ethics': { kind: 'policy', type: 'code-of-ethics', title: 'Code of Ethics', description: 'Ethical standards and expectations.', icon: CodeOfEthicsIcon, price: 3500, questions: commonQuestions },
  'company-property': { kind: 'policy', type: 'company-property', title: 'Company Property Policy', description: 'Care and use of company assets.', icon: CompanyPropertyIcon, price: 3500, questions: commonQuestions },
  'conflict-of-interest': { kind: 'policy', type: 'conflict-of-interest', title: 'Conflict of Interest Policy', description: 'Managing competing interests.', icon: ConflictOfInterestIcon, price: 3500, questions: commonQuestions },
  'deductions': { kind: 'policy', type: 'deductions', title: 'Payroll Deductions Policy', description: 'Rules for salary deductions.', icon: DeductionsIcon, price: 2500, questions: commonQuestions },
  'employee-conduct': { kind: 'policy', type: 'employee-conduct', title: 'Employee Conduct Policy', description: 'General behavioral expectations.', icon: EmployeeConductIcon, price: 3500, questions: commonQuestions },
  'family-responsibility-leave': { kind: 'policy', type: 'family-responsibility-leave', title: 'Family Responsibility Leave', description: 'Rules for family related leave.', icon: FamilyResponsibilityLeaveIcon, price: 2500, questions: commonQuestions },
  'it-cybersecurity': { kind: 'policy', type: 'it-cybersecurity', title: 'IT & Cybersecurity Policy', description: 'Securing digital assets and networks.', icon: ItCybersecurityIcon, price: 3500, questions: commonQuestions },
  'performance-management': { kind: 'policy', type: 'performance-management', title: 'Performance Management', description: 'Framework for appraisals and feedback.', icon: PerformanceManagementIcon, price: 3500, questions: commonQuestions },
  'records-retention-destruction': { kind: 'policy', type: 'records-retention-destruction', title: 'Records Retention Policy', description: 'How long to keep various documents.', icon: RecordsRetentionIcon, price: 3500, questions: commonQuestions },
  'resignation': { kind: 'policy', type: 'resignation', title: 'Resignation Policy', description: 'Procedures for voluntary termination.', icon: ResignationIcon, price: 2500, questions: commonQuestions },
  'retrenchment': { kind: 'policy', type: 'retrenchment', title: 'Retrenchment Policy', description: 'Guidelines for operational requirement dismissals.', icon: RetrenchmentIcon, price: 4500, questions: commonQuestions },
  'security': { kind: 'policy', type: 'security', title: 'Physical Security Policy', description: 'Access control and premises security.', icon: SecurityIcon, price: 3500, questions: commonQuestions },
  'travel': { kind: 'policy', type: 'travel', title: 'Travel Policy', description: 'Business travel rules and allowances.', icon: TravelIcon, price: 3500, questions: commonQuestions },
  'visitor': { kind: 'policy', type: 'visitor', title: 'Visitor Policy', description: 'Rules for guests on premises.', icon: VisitorIcon, price: 2500, questions: commonQuestions },
  'workplace-wellness': { kind: 'policy', type: 'workplace-wellness', title: 'Workplace Wellness Policy', description: 'Promoting employee health.', icon: WorkplaceWellnessIcon, price: 3500, questions: commonQuestions },
  'employee-handbook': { kind: 'policy', type: 'employee-handbook', title: 'Employee Handbook', description: 'Comprehensive guide for employees.', icon: MasterPolicyIcon, price: 5000, questions: commonQuestions },
  'it-access-security': { kind: 'policy', type: 'it-access-security', title: 'IT Access & Security', description: 'System access controls.', icon: ItAccessSecurityIcon, price: 3500, questions: commonQuestions },
  'workplace-language': { kind: 'policy', type: 'workplace-language', title: 'Language Policy', description: 'Official languages in the workplace.', icon: LanguagePolicyIcon, price: 2500, questions: commonQuestions },
  'salary-structure-guide': { kind: 'policy', type: 'salary-structure-guide', title: 'Salary Structure Guide', description: 'Compensation framework overview.', icon: SalaryStructureIcon, price: 3500, questions: commonQuestions },
  'employee-separation': { kind: 'policy', type: 'employee-separation', title: 'Employee Separation', description: 'Procedures for offboarding.', icon: EmployeeSeparationIcon, price: 3500, questions: commonQuestions },
  'compensation-benefits': { kind: 'policy', type: 'compensation-benefits', title: 'Compensation & Benefits', description: 'Remuneration policy details.', icon: CompensationBenefitsIcon, price: 3500, questions: commonQuestions },
  'data-usage-popia': { kind: 'policy', type: 'data-usage-popia', title: 'Data Usage Policy', description: 'Acceptable use of company data.', icon: DataUsageIcon, price: 3500, questions: commonQuestions },
  'communication-retention': { kind: 'policy', type: 'communication-retention', title: 'Communication Retention', description: 'Archiving business communications.', icon: CommunicationRetentionIcon, price: 3500, questions: commonQuestions },
  'certification': { kind: 'policy', type: 'certification', title: 'Certification Policy', description: 'Professional certification requirements.', icon: CertificationIcon, price: 2500, questions: commonQuestions },
  'disciplinary-action': { kind: 'policy', type: 'disciplinary-action', title: 'Disciplinary Action', description: 'Consequences for misconduct.', icon: DisciplinaryActionIcon, price: 3500, questions: commonQuestions },
  'eeo-diversity': { kind: 'policy', type: 'eeo-diversity', title: 'EEO & Diversity Policy', description: 'Equal employment opportunity.', icon: EeoDiversityIcon, price: 3500, questions: commonQuestions },
  'standby': { kind: 'policy', type: 'standby', title: 'Standby Policy', description: 'Rules for standby duty.', icon: StandbyIcon, price: 2500, questions: commonQuestions },
  'telephone-usage': { kind: 'policy', type: 'telephone-usage', title: 'Telephone Usage Policy', description: 'Use of office telephones.', icon: TelephoneUsageIcon, price: 2500, questions: commonQuestions },
  'time-off': { kind: 'policy', type: 'time-off', title: 'Time Off Policy', description: 'General time off rules.', icon: TimeOffIcon, price: 3500, questions: commonQuestions },
  'master': { kind: 'policy', type: 'master', title: 'Master HR Policy', description: 'Consolidated HR policy document.', icon: MasterPolicyIcon, price: 7500, questions: commonQuestions },
};

export const FORMS: Record<string, Form> = {
  'employment-contract': { kind: 'form', type: 'employment-contract', title: 'Employment Contract', description: 'Standard employment agreement.', icon: EmploymentContractIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'incident-report': { kind: 'form', type: 'incident-report', title: 'Incident Report', description: 'Form for reporting workplace incidents.', icon: IncidentReportIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'job-description': { kind: 'form', type: 'job-description', title: 'Job Description Template', description: 'Template for defining roles.', icon: JobDescriptionIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'leave-application': { kind: 'form', type: 'leave-application', title: 'Leave Application Form', description: 'Standard leave request form.', icon: LeaveApplicationIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'job-application': { kind: 'form', type: 'job-application', title: 'Job Application Form', description: 'Standard application for candidates.', icon: JobApplicationIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'final-written-warning': { kind: 'form', type: 'final-written-warning', title: 'Final Written Warning', description: 'Disciplinary warning form.', icon: FinalWrittenWarningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'written-warning': { kind: 'form', type: 'written-warning', title: 'Written Warning', description: 'Standard disciplinary warning.', icon: FinalWrittenWarningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'verbal-warning': { kind: 'form', type: 'verbal-warning', title: 'Verbal Warning Record', description: 'Record of verbal warning.', icon: FinalWrittenWarningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'exit-interview': { kind: 'form', type: 'exit-interview', title: 'Exit Interview Form', description: 'Questionnaire for departing staff.', icon: ExitInterviewIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'grievance-form': { kind: 'form', type: 'grievance-form', title: 'Grievance Form', description: 'Form to lodge a grievance.', icon: GrievanceIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'employee-details': { kind: 'form', type: 'employee-details', title: 'Employee Details Form', description: 'Data collection for new hires.', icon: EmployeeDetailsIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'leave-application-maternity': { kind: 'form', type: 'leave-application-maternity', title: 'Maternity Leave App.', description: 'Application for maternity leave.', icon: MaternityLeaveIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'suspension-notice': { kind: 'form', type: 'suspension-notice', title: 'Notice of Suspension', description: 'Precautionary suspension letter.', icon: SuspensionNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'appeal-form': { kind: 'form', type: 'appeal-form', title: 'Disciplinary Appeal Form', description: 'Internal appeal document.', icon: AppealFormIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'expense-claim': { kind: 'form', type: 'expense-claim', title: 'Expense Claim Form', description: 'Reimbursement request.', icon: ExpenseClaimIcon, price: 1500, questions: commonQuestions, outputFormat: 'excel' },
  'employee-training-agreement': { kind: 'form', type: 'employee-training-agreement', title: 'Training Agreement', description: 'Agreement for funded training.', icon: TrainingAgreementIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'reference-check': { kind: 'form', type: 'reference-check', title: 'Reference Check Form', description: 'Template for background checks.', icon: ReferenceCheckIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'retrenchment-notice': { kind: 'form', type: 'retrenchment-notice', title: 'Notice of Retrenchment', description: 'S189 Notice letter.', icon: RetrenchmentNoticeIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'job-advertisement': { kind: 'form', type: 'job-advertisement', title: 'Job Ad Template', description: 'Structure for job posts.', icon: JobAdvertisementIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'interview-guide': { kind: 'form', type: 'interview-guide', title: 'Interview Guide', description: 'Structured interview questions.', icon: InterviewGuideIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'candidate-evaluation': { kind: 'form', type: 'candidate-evaluation', title: 'Candidate Evaluation', description: 'Scoring sheet for interviews.', icon: CandidateEvaluationIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'onboarding-checklist': { kind: 'form', type: 'onboarding-checklist', title: 'Onboarding Checklist', description: 'Steps for new hires.', icon: OnboardingChecklistIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'confidentiality-agreement': { kind: 'form', type: 'confidentiality-agreement', title: 'NDA / Confidentiality', description: 'Non-disclosure agreement.', icon: ConfidentialityIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'restraint-of-trade': { kind: 'form', type: 'restraint-of-trade', title: 'Restraint of Trade', description: 'Non-compete agreement.', icon: RestraintOfTradeIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'performance-review': { kind: 'form', type: 'performance-review', title: 'Performance Review', description: 'Appraisal form.', icon: PerformanceReviewIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'salary-bank-details': { kind: 'form', type: 'salary-bank-details', title: 'Bank Details Form', description: 'Banking info collection.', icon: SalaryBankIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'overtime-claim': { kind: 'form', type: 'overtime-claim', title: 'Overtime Claim Form', description: 'Timesheet for overtime.', icon: OvertimeClaimIcon, price: 1500, questions: commonQuestions, outputFormat: 'excel' },
  'permission-for-deductions': { kind: 'form', type: 'permission-for-deductions', title: 'Deduction Auth', description: 'Permission to deduct from pay.', icon: PermissionForDeductionsIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'workplace-skills-plan': { kind: 'form', type: 'workplace-skills-plan', title: 'Workplace Skills Plan', description: 'WSP Template.', icon: SkillsDevelopmentIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'certificate-of-service': { kind: 'form', type: 'certificate-of-service', title: 'Certificate of Service', description: 'Proof of employment.', icon: CertificateOfServiceIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'termination-letter': { kind: 'form', type: 'termination-letter', title: 'Termination Letter', description: 'Generic dismissal letter.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'resignation-acceptance-letter': { kind: 'form', type: 'resignation-acceptance-letter', title: 'Resignation Acceptance', description: 'Response to resignation.', icon: LegalNoticeIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'payroll-processing-checklist': { kind: 'form', type: 'payroll-processing-checklist', title: 'Payroll Checklist', description: 'Monthly payroll steps.', icon: PayrollProcessingIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'disciplinary-hearing-notice': { kind: 'form', type: 'disciplinary-hearing-notice', title: 'Hearing Notice', description: 'Notice to attend disciplinary.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'meeting-minutes': { kind: 'form', type: 'staff-meeting-template', title: 'Meeting Minutes', description: 'Template for minutes.', icon: MeetingMinutesIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'disciplinary-enquiry-report': { kind: 'form', type: 'disciplinary-enquiry-report', title: 'Disciplinary Enquiry Report', description: 'Report on enquiry findings.', icon: DisciplinaryActionIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'annual-training-report': { kind: 'form', type: 'annual-training-report', title: 'Annual Training Report', description: 'Report for skills development.', icon: TrainingRegisterIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'staff-grooming-checklist': { kind: 'form', type: 'staff-grooming-checklist', title: 'Staff Grooming Checklist', description: 'Grooming standards check.', icon: ChecklistIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'warehouse-master-cleaning-checklist': { kind: 'form', type: 'warehouse-master-cleaning-checklist', title: 'Warehouse Master Cleaning', description: 'Deep clean schedule.', icon: CleaningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'master-cleaning-schedule': { kind: 'form', type: 'master-cleaning-schedule', title: 'Master Cleaning Schedule', description: 'General cleaning plan.', icon: CleaningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'food-dispatch-checklist': { kind: 'form', type: 'food-dispatch-checklist', title: 'Food Dispatch Checklist', description: 'Safety check for dispatch.', icon: FoodSafetyIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'attendance-register': { kind: 'form', type: 'attendance-register', title: 'Attendance Register', description: 'Daily attendance log.', icon: RegisterIcon, price: 1500, questions: commonQuestions, outputFormat: 'excel' },
  'warehouse-cleaning-checklist': { kind: 'form', type: 'warehouse-cleaning-checklist', title: 'Warehouse Cleaning Checklist', description: 'Routine cleaning check.', icon: CleaningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'refrigerator-temperature-logsheet': { kind: 'form', type: 'refrigerator-temperature-logsheet', title: 'Fridge Temp Log', description: 'Temperature monitoring.', icon: TemperatureIcon, price: 1500, questions: commonQuestions, outputFormat: 'excel' },
  'food-safety-training-modules': { kind: 'form', type: 'food-safety-training-modules', title: 'Food Safety Modules', description: 'Training content outline.', icon: FoodSafetyIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'thermometer-verification-checklist': { kind: 'form', type: 'thermometer-verification-checklist', title: 'Thermometer Verification', description: 'Calibration check.', icon: TemperatureIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'cleaning-checklist': { kind: 'form', type: 'cleaning-checklist', title: 'Cleaning Checklist', description: 'General area cleaning.', icon: CleaningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'food-receiving-checklist': { kind: 'form', type: 'food-receiving-checklist', title: 'Food Receiving Checklist', description: 'Delivery inspection.', icon: FoodSafetyIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'bar-master-cleaning-schedule': { kind: 'form', type: 'bar-master-cleaning-schedule', title: 'Bar Master Cleaning', description: 'Bar area deep clean.', icon: CleaningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'bar-cleaning-checklist': { kind: 'form', type: 'bar-cleaning-checklist', title: 'Bar Cleaning Checklist', description: 'Routine bar cleaning.', icon: CleaningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'food-safety-training-register': { kind: 'form', type: 'food-safety-training-register', title: 'Food Safety Training Reg.', description: 'Training attendance log.', icon: TrainingRegisterIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'leave-register': { kind: 'form', type: 'leave-register', title: 'Leave Register', description: 'Track employee leave.', icon: RegisterIcon, price: 1500, questions: commonQuestions, outputFormat: 'excel' },
  'voluntary-retrenchment-application': { kind: 'form', type: 'voluntary-retrenchment-application', title: 'Voluntary Retrenchment App', description: 'Application for VSP.', icon: RetrenchmentNoticeIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'hr-bundle-package': { kind: 'form', type: 'hr-bundle-package', title: 'HR Bundle Package', description: 'Essential HR forms.', icon: BundleIcon, price: 5000, questions: commonQuestions, outputFormat: 'word' },
  'employee-handbook-canva': { kind: 'form', type: 'employee-handbook-canva', title: 'Employee Handbook (Canva)', description: 'Visual handbook template.', icon: CanvaIcon, price: 3500, questions: commonQuestions, outputFormat: 'word' },
  'anticipated-retrenchment-notice': { kind: 'form', type: 'anticipated-retrenchment-notice', title: 'Anticipated Retrenchment', description: 'Initial S189 notice.', icon: RetrenchmentNoticeIcon, price: 2500, questions: commonQuestions, outputFormat: 'word' },
  'onboarding-checklist-canva': { kind: 'form', type: 'onboarding-checklist-canva', title: 'Onboarding Checklist (Canva)', description: 'Visual onboarding list.', icon: CanvaIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'employee-survey-canva': { kind: 'form', type: 'employee-survey-canva', title: 'Employee Survey (Canva)', description: 'Visual survey template.', icon: CanvaIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'employee-review-canva': { kind: 'form', type: 'employee-review-canva', title: 'Employee Review (Canva)', description: 'Visual review template.', icon: CanvaIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'daily-attendance-canva': { kind: 'form', type: 'daily-attendance-canva', title: 'Daily Attendance (Canva)', description: 'Visual attendance tracker.', icon: CanvaIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'verbal-warning-afrikaans': { kind: 'form', type: 'verbal-warning-afrikaans', title: 'Verbal Warning (Afrikaans)', description: 'Waarskuwing in Afrikaans.', icon: AfrikaansIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'fixed-contract-ending-notice': { kind: 'form', type: 'fixed-contract-ending-notice', title: 'Fixed Contract Ending', description: 'Notice of non-renewal.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'consultation-meeting-notice': { kind: 'form', type: 'consultation-meeting-notice', title: 'Consultation Notice', description: 'Invite to S189 consultation.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'grievance-investigation-notice': { kind: 'form', type: 'grievance-investigation-notice', title: 'Grievance Investigation', description: 'Notice of investigation.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'incapacity-inquiry-general-notice': { kind: 'form', type: 'incapacity-inquiry-general-notice', title: 'Incapacity Inquiry Notice', description: 'Notice for general incapacity.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'incapacity-inquiry-ill-health-notice': { kind: 'form', type: 'incapacity-inquiry-ill-health-notice', title: 'Ill Health Inquiry Notice', description: 'Notice for ill health enquiry.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'poor-performance-inquiry-notice': { kind: 'form', type: 'poor-performance-inquiry-notice', title: 'Poor Performance Notice', description: 'Notice for performance enquiry.', icon: LegalNoticeIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'postponement-of-hearing-notice': { kind: 'form', type: 'postponement-of-hearing-notice', title: 'Postponement Notice', description: 'Notice to postpone hearing.', icon: LegalNoticeIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'observation-report': { kind: 'form', type: 'observation-report', title: 'Observation Report', description: 'Report on observation.', icon: IncidentReportIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'staff-meeting-template': { kind: 'form', type: 'staff-meeting-template', title: 'Staff Meeting Template', description: 'Agenda and minutes.', icon: MeetingMinutesIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'medical-report-template': { kind: 'form', type: 'medical-report-template', title: 'Medical Report Template', description: 'Template for medical feedback.', icon: IncidentReportIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'grievance-decision-form': { kind: 'form', type: 'grievance-decision-form', title: 'Grievance Decision', description: 'Outcome of grievance.', icon: GrievanceIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'poor-performance-meeting-minutes': { kind: 'form', type: 'poor-performance-meeting-minutes', title: 'Performance Minutes', description: 'Minutes for performance meeting.', icon: MeetingMinutesIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'final-warning-hearing-held': { kind: 'form', type: 'final-warning-hearing-held', title: 'Final Warning (Hearing)', description: 'Outcome after hearing.', icon: FinalWrittenWarningIcon, price: 1500, questions: commonQuestions, outputFormat: 'word' },
  'incident-investigation-report': { kind: 'form', type: 'incident-investigation-report', title: 'Incident Investigation', description: 'Detailed investigation report.', icon: IncidentReportIcon, price: 2000, questions: commonQuestions, outputFormat: 'word' },
  'confidentiality-ip-agreement': {
    kind: 'form',
    type: 'confidentiality-ip-agreement',
    title: 'Confidentiality & IP Agreement',
    description: 'Protect company secrets and intellectual property.',
    icon: ConfidentialityIcon,
    price: 2500,
    questions: [
      ...commonQuestions,
      { id: 'includeNonCompete', label: 'Include Non-Compete Clause?', type: 'checkbox', tip: 'Restrict employees from working for competitors after leaving.' },
      { id: 'includeNonSolicit', label: 'Include Non-Solicitation Clause?', type: 'checkbox', tip: 'Prevent poaching of clients or staff.' }
    ],
    outputFormat: 'word'
  },
};

export const POLICY_CATEGORIES = [
  {
    title: 'All Policies',
    items: Object.values(POLICIES)
  }
];

export const FORM_CATEGORIES = [
  {
    title: 'All Forms',
    items: Object.values(FORMS)
  }
];
